version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: mustermann
      POSTGRES_PASSWORD: mustermann
      POSTGRES_DB: todoapp
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - todoapp-network
    restart: always

  backend:
    build: ./todo-backend
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      PGUSER: mustermann
      PGHOST: database
      PGDATABASE: todoapp
      PGPASSWORD: mustermann
      PGPORT: 5432
    networks:
      - todoapp-network
    restart: always

    working_dir: /app
    volumes:
      - ./todo-backend:/app

  frontend:
    build: ./todo-app
    ports:
      - "3000:3000"
    networks:
      - todoapp-network
    restart: always

  test:
    build: ./todo-backend
    command: npm test
    depends_on:
      - database
    environment:
      PGUSER: mustermann
      PGHOST: database
      PGDATABASE: todoapp
      PGPASSWORD: mustermann
      PGPORT: 5432
    networks:
      - todoapp-network
    restart: on-failure
    working_dir: /app
    volumes:
      - ./todo-backend:/app

networks:
  todoapp-network:

volumes:
  db-data: